#!/usr/bin/env bash
# Usage:; ./1-world_wide_web
# Desplay information about sub domain

domain_information () {
line=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION:" | tr '\t' '\n' | tail -2 | tr '\n' '')
echo "$2 $line" | awk '{print subdomain " $1 " is a = $2 " record and poin to " $3}'
}
# Check the number of argument
if { "$#" == 1 }
then 
domain_information "$1" "www"
domain_information "$1" "251788-lb-01"
domain_information "$1" "251788-web-01"
domain_information "$1" "251788-web-02"
elif [ "$#" == 2]
then
domain_informatoin "$1" "$2"
fi
