#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 251788-web-02 18.234.105.122 check
        server 251788-lb-01 54.236.86.20 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
