#!/usr/bin/env bash
#configure nginx server to listen for port 80

# remove the defaoult configuration file
rm /etc/nginx/sites-enabled/default
#configre nginx to port 18
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default/etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
